### ISSUE TITLE
Is this repository working or is it still in development? TAILWIND_MODE errors.

### ISSUE THREAD

**Issue by marcivanmanalac** [roboflow-ai/dji-aerial-georeferencing#13]
I've read the [blog post](https://blog.roboflow.com/georeferencing-drone-videos/) on roboflow and tried to follow along on the _Try it in your Browser_ and _Run it Locally_ guide in the ReadMe, but am having difficulties getting them to work. More specifically, the deployed GitHub page does not exist, and running the `npm run build:dev` returns TAILWIND_MODE errors. 

I've also included screenshots of my outputs in the Roboflow [forums](https://discuss.roboflow.com/t/using-computer-vision-with-drones-for-georeferencing-tutorial-broken/1684) post.

**Comment by yeldarby** [comment]
Thanks for pointing out the broken link; our github URL recently changed from `roboflow-ai` to `roboflow` so the gh-pages link is now: https://roboflow.github.io/dji-aerial-georeferencing/

And just tested that it appears working for me both on the deployed version & locally (and in the github action [as of this morning when we merged in some dependabot fixes](https://github.com/roboflow/dji-aerial-georeferencing/actions/workflows/webpack.yml)).

If you post the full error message you're getting I might be able to point you in the right direction.

**Comment by yeldarby** [comment]
Fixed the README in #14

**Comment by marcivanmanalac** [comment]
Thank you for your quick response. 

This is the error message I am receiving:
![image](https://user-images.githubusercontent.com/111533234/225460754-d68b955f-5a8e-43b3-957a-6ed9082168a2.png)


I ran npm install already within the cloned repo

**Comment by RobertoNovelo** [comment]
Hello @marcivanmanalac ! It looks like the command is not compatible with your Windows shell. Could I suggest trying with `WSL`? Otherwise, you might need to install something like `cross-env`, and update the command to something along the lines of `"start": "cross-env TAILWIND_MODE=watch ......"`

**Comment by marcivanmanalac** [comment]
> Hello @marcivanmanalac ! It looks like the command is not compatible with your Windows shell. Could I suggest trying with `WSL`? Otherwise, you might need to install something like `cross-env`, and update the command to something along the lines of `"start": "cross-env TAILWIND_MODE=watch ......"`

Thank you! I was able to get it to work using cross-env
