### ISSUE TITLE
How to accomodate for camer tilit ?

### ISSUE THREAD

**Issue by FawadAbbas12** [roboflow-ai/dji-aerial-georeferencing#17]
Thanks for ope-sourcing your work.
I have a question regarding camera movement for your current implementation you are assuming that camera is looking down thus drone's position will always be in the center of image but how can we adjust the position error when our drone is looking at an angle.
If possible can you also recommend any book or resource.

**Comment by yeldarby** [comment]
Hi, this will be hard to do accurately because you’d need a full 3D topography map and have to do a lot of math. I won’t be able to add it but if you get it working please submit a PR!

**Comment by FawadAbbas12** [comment]
Sure i will :)
